- components/Ansible.php
- components/Command.php
- components/Folder.php
- components/Task.php
- config/params.php
- console/WalleController.php
- controllers/ConfController.php
- controllers/WalleController.php
- messages/en/conf.php
- messages/en/walle.php
- messages/zh/conf.php
- messages/zh/walle.php
- migrations/m160307_082032_ansible.php
- models/Project.php
- views/conf/edit.php
- views/conf/preview.php
- views/walle/check.php
1、宿主机安装 ansible
```
yum install ansible # RHEL/CentOS/Fedora
apt-get install ansible # Debian/Ubuntu
emerge -avt ansible  # Gentoo/Funtoo
pip install ansible # will also install  paramiko PyYAML jinja2
```
2、宿主机无需其他配置，兼容 ~/.ssh/config 名称、证书配置
3、目标机无需额外配置
1. 项目配置 中 开启Ansible
2. (可选) config/params.php 配置 ansible_hosts 文件存放路径
3. 按正常流程发布、上线代码，传输文件、远程执行命令均会通过ansible并发执行
git 仓库 300M 左右的代码文件，php文件为主，包含很多 vendor
局域网内 14台目标机
反复对同一个版本，开关ansible支持，多次上线对比 start-deploy 接口总耗时
`关闭ansible: 平均每次 3分43秒`
`开启ansible: 平均每次 1分29秒`
1、messages/en/conf.php 语言包不完善
2、svn 传输文件时，无论选择上线哪些文件，均会传输整个仓库目录中的文件
> 支持 ansible 并发发布文件、执行远程命令

- components/Svn.php
config/local.php 中设置了 putenv('LC_ALL=zh_CN.UTF-8');
但是我的ubuntu系统的env是 en_US.UTF-8
于是 svn 的所有命令都会输出如下警告
```
svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LC_ALL is zh_CN.UTF-8
svn: warning: please check that your locale name is correct
```
导致获取 svn 历史记录，解析 xml 失败，提示
```
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found
```
解决办法：
1、svn 命令设置 LC_ALL=C
2、xml解析查找以<?xml 开头
第一种解决方法，需要多测试下，是不是可行，中文注释会不会乱码之类的
> svn env LC_ALL 设置问题

- components/Git.php
- views/task/submit-git.php
bug重现：
创建新分支 feature 分支，在feature分支上进行开发，将feature分支发布到测试线测试
当feature开发完成，合并到master分支，并且删除remote上的feature分支后，再对项目进行发布，会出现发布页面选中的依然是feature分支，并且刷新分支会失败
> fix: 当remote 删除当前分支后，刷新分支会失败

- Dockerfile
- apache2.conf
- config/local.php
- config/params.php
- entrypoint.sh
- php.ini
增加增加Docker镜像构建文件，可以构建Docker镜像。
配置信息通过以下环境变量设置：
`WALLE_DB_DSN` - 数据库DSN
`WALLE_DB_USER` - 数据库用户名
`WALLE_DB_PASS` - 数据库密码
`WALLE_MAIL_HOST` - 邮件服务器
`WALLE_MAIL_USER` - 邮件用户名
`WALLE_MAIL_PASS` - 邮件密码
`WALLE_MAIL_PORT` - 邮件端口
`WALLE_MAIL_ENCRYPTION` - 邮件加密方式
`WALLE_MAIL_EMAIL` - 邮件地址
`WALLE_LANGUAGE` - 语言
`WALLE_LOG_PATH` - 日志目录
`WALLE_ANSIBLE_HOSTS_DIR` - Ansible Hosts 主机列表目录
我在[https://hub.docker.com/r/starlight36/walle-web/](https://hub.docker.com/r/starlight36/walle-web/)上做了一个镜像，可以通过这个docker-compose.yml使用。
```yml
walle:
image: starlight36/walle-web
environment:
- "WALLE_DB_DSN=mysql:host=localhost;dbname=walle_production"
- "WALLE_DB_USER=walle"
- "WALLE_DB_PASS=walle"
ports:
- "80:80"
restart: always
```
> 增加Docker镜像构建文件

- components/Git.php
Before fetching, remove any remote-tracking references that no longer exist on the remote.
@see https://git-scm.com/docs/git-fetch
> remove any references that not exist on the remote

- views/conf/index.php
- views/task/list.php
在小分辨率下。那些操作按钮都无法显示。所以直接去掉这几个css
> [修改]项目配置页面，上线单页面操作按钮小分辨率也支持显示

- controllers/TaskController.php
- models/Task.php
回滚时生成数据记录的commit_id为回滚数据行的commit_id, 并不是当前版本的commit_id。导致列表页看到的commit_id并不是当前线上版本的commit_id，不方便查看。
> fixed:多次回滚后， 显示不了当前版本标记

- controllers/TaskController.php
when walle deployed under a sub-path like http://localhost/walle, the TaskController.actionRollback return a wrong new deplay url http://localhost/walle/deploy?taskId=10 which actually shoud be http://localhost/walle/walle/deploy?taskId=10
> fix actionRollback return url

- components/Folder.php
- models/Project.php
> fixbug#317 发布目录不用git仓库名称，改成project_id

- admin.sh
> 修复升级数据库脚本的bug

- .travis.yml
- requirements/dev.txt
- walle/model/database.py
- walle/service/utils.py
__# noqa__ will placate flake8
flake8 on Python 2 has a real problem linting __walle/model/database.py__ so this PR adds a __noqa__.
Updated some dev dependencies and removed __flake8-blind-except__ as redundant.
> One more noqa because reload() was moved in Python 3

- walle/app.py
socketio.run 这个方法假如传入debug=True的话, 在python3.6环境下跑, 启动的时候会报一个 MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6
这个错误会影响实际的使用, 所以至少生产环境版本应该把这个DEBUG设置为false
> 修复在python3.6环境下, 启动flask_socketio报错的问题

- walle/api/task.py
fix the error when rollback by remove blank in task name:
bash: line 0: export: `-': not a valid identifier
bash: line 0: export: `回滚此次上线': not a valid identifier
> change rollback task name

- walle/service/deployer.py
- walle/service/git/repo.py
这个分析判断是路径错误，因为先cd进了target_releases目录，然后在创建软链时的相对路径又使用了target_releases目录。
但是只有一个人提了Issues，需要再验证。
> 2.1/bugfix/创建软链失败

- walle/api/passport.py
> 修复bug，未分配用户登录的时候，前端提示服务器错误。改为提示具体的错误信息。

- walle/model/member.py
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 2") [SQL: 'SELECT users.id AS users_id, users.username AS users_username, users.is_email_verified AS users_is_email_verified, users.email AS users_email, users.password AS users_password, users.avatar AS users_avatar, users.`role` AS users_role, users.status AS users_status, users.last_space AS users_last_space, users.created_at AS users_created_at, users.updated_at AS users_updated_at, members.access_level AS members_access_level FROM users INNER JOIN members ON users.id = members.user_id WHERE users.status NOT IN (%s) AND members.source_id = %s AND …
> 解决 项目管理 》成员管理 添加成员 失败的bug

- walle/app.py
让 flask 的 web 服务以多线程的方式启动。让主线程继续执行启动  socket 后的逻辑（否则主线程会在启动 socketio 这里一直阻塞，后续的逻辑是不会被执行的）。
> 让 flask 的 web 服务以多线程的方式启动。

- admin.sh
ubuntu 高版本 sh 指向的是 dash 而非 bash。 dash 无法使用 function 关键字以及 source 等命令。
在 admin 脚本中，如果检测到 sh 指向的是 dash， 那么将使用 bash 重新执行脚本，然后在参数末尾加上一个 flag， 表示此次运行是修正过的， 避免陷入死循环。
另一个修复方式是将 admin 脚本中的 funcation 关键字全部删掉，然后用 . 替换  source 关键字。但是这样会让 admin.sh 文件语法限制收紧。
> 修复 ubuntu 高版本下使用 sh 命令执行 admin.sh 脚本报错的 bug。

- walle/api/space.py
- walle/model/member.py
bug:https://github.com/meolu/walle-web/issues/824
bug 原因：超级管理员给某个空间赋值给某个用户后，members 表中的数据没有及时更新导致此用户仍然不属于此空间。
修复：在更新 space 的时候，判断一下新旧的 owner，如果有差异的话，先将 owner 更新一下。
> 修复 bug：#824。超级管理员给某个空间赋值给某个用户后，members 表中的数据没有及时更新导致此用户仍然不属于此空间。

- walle/api/api.py
- walle/api/passport.py
- walle/config/settings.py
- walle/config/settings_dev.py
- walle/config/settings_prod.py
- walle/config/settings_test.py
添加cookie配置，减少浏览器退出时需要重输密码次数。
core: use "remember = True" config on flask_login package.
测试时发现在SecurityResource中需要fresh_session,之前这一步操作是在login中完成的。
测试环境连不上，无法进行测试环境测试。
这里没有进行过期时间配置，默认是365天。可以在配置文件中选择开启。
> 添加cookie配置

- requirements/prod.txt
Fix ERROR: babel 2.7.0 has requirement pytz>=2015.7, but you'll have pytz 2015.6 which is incompatible.
> 更新 pytz 依赖版本，避免初始化时的错误

- walle/service/git/repo.py
```
>>git checkout tag-xxx
>>git pull
```
```
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.
git pull <remote> <branch>
```
> 解决 已克隆项目切换到tag后下次初始化仓库直接git pull 报错问题。

- .travis.yml
Modules that are imported but not used slow down our processing.
https://flake8.pycqa.org/en/latest/user/error-codes.html
> Travis CI: Look for unused imports
