meolu/walle-web

- views/task/list.php
> 回滚按钮改成文成也可点击

- messages/en/w.php
- messages/zh/w.php
- views/layouts/site.php
- views/site/login.php
- views/site/requestPasswordResetToken.php
- views/site/signup.php
- views/user/resetPassword.php
Think this one should be 'cleaner' :)
> cleaned translations

- .gitignore
- config/local.php
- config/web.php
- tests/codeception/config/acceptance.php
- tests/codeception/config/functional.php
- tests/codeception/config/unit.php
Move credentials to `config/local.php` and add this file to .gitignore for easier modification and development without accidental pushing credentials to github.
I've also added language setting to local.php so developers can change all language related settings in one file
> Local credentials

- docs/install.md
> 设置mysql连接密码

- docs/install.md
> 补充默认用户名和密码

- components/EventBootstrap.php
- components/GlobalHelper.php
- controllers/ConfController.php
- controllers/TaskController.php
- controllers/UserController.php
- views/conf/detection.php
- views/conf/group.php
- views/conf/index.php
- views/layouts/main.php
- views/layouts/modal.php
- views/layouts/site.php
- views/site/error.php
- views/site/login.php
- views/site/requestPasswordResetToken.php
- views/site/signup.php
- views/task/list.php
- views/task/select-project.php
- views/task/submit-git.php
- views/task/submit-svn.php
- views/user/audit.php
- views/user/index.php
- views/walle/check.php
- views/walle/deploy.php
supports the use of relative URLs
> supports the use of relative URLs

- components/GlobalHelper.php
Task Scheduler command support using "#" comment
> Task Scheduler command support using "#" comment

- web/.gitignore
> add .gitignore entry to ignore assets files

- controllers/TaskController.php
> 修正任务列表分页只能显示10条的bug

- .gitignore
- controllers/TaskController.php
- views/task/select-project.php
- 移除了一处重复定义的变量（没有用的数据库查询）
- 解决任务列表分页显示时，修改每页数量后点击第二页时，每页数量自动变为10的BUG
- 项目选择界面修正预发布环境和线上环境部分项目选择按钮多行重叠的BUG
> 修正分页BUG以及几处页面错误

- controllers/ConfController.php
- models/Project.php
> 使用模型验证进行字段过滤

- controllers/ConfController.php
- views/conf/index.php
1. 修改项目配置，管理员可以查看并配置项目
2. 修复url跳转中一个绝对url的小bug
> 修改项目配置，管理员可以查看并更改项目

- components/Command.php
- controllers/TaskController.php
- controllers/WalleController.php
- messages/en/task.php
- messages/en/walle.php
- messages/zh-CN/task.php
- messages/zh-CN/walle.php
- views/task/list.php
- views/walle/check.php
1. 上线单列表增加按项目名称筛选
2. 审核状态改变页面自动刷新
3. 线上文件指纹获取增加为空验证
> 上线单列表增加按项目名称筛选

- config/local.php
处理ENV变不存在的情况，密码使用BASE64编码处理特殊字符
> config update

- controllers/WalleController.php
> fix Undefined index: command in controllers/WalleController.php:379

- controllers/ConfController.php
重现步骤
1. 点击成员
2. 添加成员
3. 点击删除
4. 删除之后，f5 刷新，会发现删除的成员又出现了。
> fix 删除项目成员 bug

- components/Git.php
> Feature gitlog time

- walle/model/menu.py
- walle/model/space.py
> #532 修复一些不兼容3.0问题

- README.md
If you like it, feel free to merge it :)
> Added a visualisation of code

- walle/api/user.py
- walle/form/user.py
1. 用户名未做是否被注册的校验，导致 insert 用户实体的时候报错
2. 给注册成功的用户发送邮件，后台邮件服务器错误，导致前端提示错误。
> 修复 bug 用户注册的时候提示错误。两处错误：

- walle/form/user.py
> fix #772 修改密码后，新密码无法登录 (登录时密码做了位数验证)

- admin.sh
参见：https://anerg.com/2019/03/%E5%9C%A8%E6%A0%91%E8%8E%93%E6%B4%BE3b%E4%B8%8A%E9%83%A8%E7%BD%B2walle2-0/
> 增加树莓派的系统支持

- walle/service/deployer.py
ssh-keygen 默认生成的文件为 id_rsa.pub，troubleshooting 描述的也为 id_rsa.pub
> chore: 修改描述

- admin.sh
- requirements/prod.txt
- walle/config/settings_prod.py
- walle/service/deployer.py
- walle/service/extensions.py
1. 项目管理中自定义全局变量=两边可以有空格,建议创建项目时做校验
2. socketio 跨域问题，解决xxx is not an allow origin报错
3. 增加requirement中pymysql包
4. centos7 依赖安装报错解决, 增加豆瓣python源
5. admin.sh中增加requrie命令用于安装依赖python包
> fix some bugs

- admin.sh
- requirements/prod.txt
> fix GitPython版本问题

- .travis.yml
- walle/config/settings_prod.py
- walle/service/deployer.py
改动:
删除版本数错误, 修改Mysql配置。
测试:
修改后Mysql启动正常。
执行一次上线单查看命令执行正常。
> walle 2.1 - fix #1008 删除版本数错误, 修改Mysql配置
